server:
  port: 8189
  servlet:
    context-path: /
jwt:
  secret: 8w475hg8w47hg457h98754hg8w3127hwo358hg
  lifetime: 180000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketdb
    username: sergioramos4
    password: 221001
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        format_sql: true
